### ISSUE TITLE
Determine which node test framework to use

### ISSUE THREAD

**Issue by Krondo** [Krondo/Untitled#1]
1. Look into Mocha
2. Continue with Jasmine/Karma

**Comment by Krondo** [comment]
Will be using mocha for node unit testing.

**Comment by Krondo** [comment]
JK I meant Jasmine

**Comment by tval488** [comment]
1. Look into steps into establishing LLC. 
2. Gain contact with community colleges for outreach.
3. Contact scholarship foundation for any and all help.

**Comment by Krondo** [comment]
I have decided to implement Jasmine as our testing framework and will include the following dev modules
- Mjackson's Expect: for assertions
- Rewire: for mocking data/ method calls
- SuperTest: For routes and endpoints
