### ISSUE TITLE
Create stage and develop branches / review PR's

### ISSUE THREAD

**Issue by Krondo** [Krondo/Untitled#12]
@dube77 In a typical web development lifecycle, you will often see three branches of focus where work is done. 
- Develop: where you develop new components
- Stage: where you test newly developed features / QA testing phase
- Master/Production where the final product sits

The power in Git version control is truly reflected in its ability to create branches. Branches are exact copies of a file structure that you can then make changes on without affecting the original copy of the code base. Typically a development life cycle looks like this.

- A developer makes a branch off of the develop branch by first using `git checkout develop` to assure they are on the develop branch, using `git pull` to assure the develop branch on their local is up to date with the develop branch on the repo.
- The next step is to create a new branch using the `-b` flag. The statement would look like this `git checkout -b 'My new branch'`
- A developer would then create a new feature on this branch and when it is ready, they open up a Pull request on github (Commonly referred to as PR) Other developers then read through the changes and then make comments on the PR if any changes need to be brought to light
- When code is ready to be Merged with another branch it is typically kosher to have another developer comment on the PR with a '+1' to let other developers know that the code has been double checked and meets the quality standards.
- A developer (typically the QA guy) then merges the developers branch with the new feature into the develop branch on the repo.
- From there, the develop branch is merged into stage for testing and then from stage to master once testing is completed. This is the ebb and flow of the modern development life cycle

I will walk through this step with you in the near future to get you familiar with creating branches and retrieving / sending data to the git repo.

**Comment by dube77** [comment]
I did quite a lot with Git version control in my Design Patterns class when working in groups. I'm quite familiar with the process you stated above but will accept the walk through.

**Comment by Krondo** [comment]
@dube77 awesome, more or less I wanted to walk you through the PR process to make sure we are on the same page of how and when we merge a PR
