### ISSUE TITLE
Install Node.js on your local environment and run our app locally

### ISSUE THREAD

**Issue by Krondo** [Krondo/Untitled#8]
- Visit nodes site to learn about node and how to install node on your machine
- Once installed, navigate to the root directory of our app and run the command `npm install` This will install all node module dependencies located in the package.json file.
- Read up on what package.json is and why it is important
- After you have run init you should be able to start up your local env by running `node server.js` from the root directory of the project.
- in your browser navigate to localhost:3000 to confirm that you have successfully started the webapp locally

**Comment by Krondo** [comment]
Node.js is a powerful event loop driven single threaded non blocking I/O that is built on googles V8 javascript engine. The engine is written in c++ and Node itself is essentially javascript that runs on the server which is why it has become so popular with full stack developers. In the past with webservers that run PHP and apache, when you wanted to perform asynchronous coding tasks this required you to create another thread which in turn chewed up a lot of system resources. With node, you can run asynchronous code by registering a callback that will be added back to the system stack by the event loop once the function is ready to complete and return a value. No need to multi thread your applications which is why node is extremely scalable and used world wide. I would advise looking further into what asynchronous coding is and what a javascript callback is in terms of ES6. 

A good starter example of a callback can be found in the server.js file under the handlers section
`app.get('/about', (req, res) => {
  res.render('about.hbs', {
    pageTitle: 'About Page'
  });
});`
where the get function takes a parameter, in this case requesting file path and gets second parameter is a function that runs after get completes its job. The callback will receive two parameters from get which is request and response which is then used to render the page. If the callback stuff is confusing don't worry about it for now, takes a while of working with them for the clarity to sink in.

**Comment by dube77** [comment]
Error with starting server.js : https://i.imgur.com/Us6o90m.png
Callbacks aren't quite clear (i know you said not to worry about it for now) I need it to be explained to me like I'm 5, not really, but sorta.

**Comment by Krondo** [comment]
@dube77 did you run npm install? It's looking for express which is a node module that gets installed from the package.json file.

**Comment by dube77** [comment]
lol, i didn't apparently. thought i did

**Comment by Krondo** [comment]
@dube77 no my apologies there bud, I put `npm init` in the instructions. `npm init` creates a default package.json file if one does not already exist. `npm install` will look at the package.json file and install the node module dependencies. This is the command I intended for you to run
